name: "Dotnet build"
description: "Realiza el Restore, build y test"
inputs:
  github_username:
    description: "usuario de github para autenticarse en los packages"
    required: true
  github_token:
    description: "token del usuario con permisos de lectura en packages"
    required: true
  workdir_src:
    description: "directorio donde se encuentra el project a compilar DEFAULT: ./src"
    required: false
    default: './src'
  workdir_test:
    description: "directorio donde se encuentra los test DEFAULT: ./test"
    required: false
    default: './test'
runs:
  using: "composite"
  steps:
      - run: echo hi!, we working.
        shell: bash
        # Setup .NET Core SDK
